apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-data
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/jenkins-home
