kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: jenkins
      role: host-mount

